name: ci
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install pylint
      run: |
        sudo apt update -y
        python -m pip install --upgrade pip
        pip install pylint
    - uses: pre-commit/action@v3.0.0
    
